# Project Information
site_name: BTD6 Wiki
site_description: 气球塔防6（BTD6）攻略站，提供入门到精通的简介和攻略。
site_author: EndlessLethe
site_url: https://github.com/BTD6wiki/BTD6-wiki
strict: false

# Repository
repo_name: 'BTD6-wiki'
repo_url: 'https://github.com/BTD6wiki/BTD6-wiki'
edit_uri: 'https://btd6wiki.github.io/BTD6-wiki/edit-landing/?ref='

# Contents
nav:
  - 简介:
    - 关于Wiki: index.md
    - 如何开始游戏: intro/how_to_start.md
    - 萌新常见问题的解答: intro/FQA.md
    - 如何贡献内容: intro/how_to_contribute.md
    - 致谢: intro/thanks.md
  - 游戏机制:
    - 英雄: 
    # 和游戏内英雄顺序保持一致
      - 英雄简介: basic/heroes/heroes.md
      - 昆西: basic/heroes/1_Quincy.md
      - 格温多琳: basic/heroes/2_Gwendolin.md
      - 先锋琼斯: basic/heroes/3_Striker_Jones.md
      - 奥本·格林福特: basic/heroes/4_Obyn_Greenfoot.md
      - 灵机: basic/heroes/13_Psi.md
      - 上尉丘吉尔: basic/heroes/5_Captain_Churchill.md
      - 本杰明: basic/heroes/6_Benjamin.md
      - 艾泽里: basic/heroes/7_Ezili.md
      - 帕特·法斯第: basic/heroes/8_Pat_Fusty.md
      - 阿多拉: basic/heroes/9_Adora.md
      - 海军上将布里克尔: basic/heroes/10_Admiral_Brickell.md
      - 艾蒂安: basic/heroes/11_Etienne.md
      - 萨乌达: basic/heroes/12_Sauda.md
    - 力量:
      - 力量: basic/powers/powers.md
      - insta猴子: basic/powers/insta.md
    - 知识: 
      - 知识简介: basic/knowledge/knowledge.md
      - 初级: basic/knowledge/primary.md
      - 军事: basic/knowledge/military.md
      - 魔法: basic/knowledge/magic.md
      - 支持: basic/knowledge/support.md
      - 英雄: basic/knowledge/heroes.md
      - 力量: basic/knowledge/powers.md
    - 气球类型: basic/bloons.md
    - 伤害类型: basic/damage.md
    - 攻击: basic/attack.md
    - 道具: basic/items.md
    - 游戏模式: basic/mods.md
    - 波次: basic/waves.md
    - 经济系统: basic/economy.md
    - 成就: basic/achievements.md
  - 猴子防御塔:
    - 猴子一览: monkeys/monkeys.md
    - 初级猴子:
      - 初级猴子简介: monkeys/primary/primary.md
      - 飞镖猴: monkeys/primary/1_dart_monkey.md
      - 回旋镖猴: monkeys/primary/2_boomerang_monkey.md
      - 大炮: monkeys/primary/3_bomb_shooter.md
      - 图钉塔: monkeys/primary/4_tack_shooter.md
      - 冰冻猴: monkeys/primary/5_ice_monkey.md
      - 胶水猴: monkeys/primary/6_glue_gunner.md
    - 军事猴子:
      - 狙击手猴: monkeys/military/1_sniper_monkey.md
      - 猴子潜艇: monkeys/military/2_monkey_sub.md
      - 海盗猴: monkeys/military/3_monkey_buccaneer.md
      - 皇家飞行员: monkeys/military/4_monkey_ace.md
      - 直升机飞行员: monkeys/military/5_heli_pilot.md
      - 迫击炮猴: monkeys/military/6_mortar_monkey.md
      - 机枪猴: monkeys/military/7_dartling_gunner.md
    - 特殊猴子:
      - 六级猴子(典范猴): monkeys/special/paragon.md
      - 神殿: monkeys/special/temple.md
  - 战术搭配:
      - 搭配的基本逻辑: collocation/first_class.md
      - 1 太阳永啤流: collocation/1_tai_yang_yong_pi_liu.md
      - 2 军事流: collocation/2_jun_shi_liu.md
      - 3 六德流: collocation/3_liu_de_liu.md
      - 4 大炮流: collocation/4_da_pao_liu.md
      - 5 忍者流: collocation/5_ren_zhe_liu.md
      - 6 图钉流: collocation/6_tu_ding_liu.md
      - 7 永钉流: collocation/7_yong_ding_liu.md
  - 进阶内容:
      - 征途模式: advance/odyssey_mode.md
      - 每日任务: advance/everyday.md
      - BOSS挑战: advance/boss_challenge.md
      - 竞速模式: advance/race_event.md
      - freeplay: advance/freeplay.md

# Theme
theme:
  name: material
#   custom_dir: 'mkdocs-material/material'
  static_templates:
    - 404.html
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  include_search_page: false
  search_index_only: true
  favicon: 'https://cdn.jsdelivr.net/npm/oicdn@0.0.1/favicon.ico'

  logo: 'school'
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde